### ISSUE TITLE
Failed to activate the package-js-generator package

### ISSUE THREAD

**Issue by BorisKozo** [Nicolab/atom-package-js-generator#3]
Is this package maintained?
It doesn't work straight from install :)
And I really dislike coffeescript

**Atom Version**: 1.0.3
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [package-js-generator](https://github.com/Nicolab/atom-package-js-generator) package, v1.5.0
### Stack Trace

Failed to activate the package-js-generator package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at Object.module.exports.extends (C:\Users\boris\.atom\packages\package-js-generator\node_modules\atom-helpers\lib\utils.js:25:26)
    at Object.<anonymous> (C:\Users\boris\.atom\packages\package-js-generator\lib\package-js-generator-view.js:28:16)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\boris\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\boris\.atom\packages\package-js-generator\lib\package-js-generator.js:8:30)
    at Module._compile (module.js:452:26)
```
### Commands

```
     -0:07.6.0 package-js-generator:generate-package (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "package-generator"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
package-js-generator, v1.5.0

# Dev
No dev packages
```

**Comment by Nicolab** [comment]
Hello,

It has not been migrated to the new API of Atom V1. 
Sorry, for now, I do not have time to migrate.

**Comment by zedtux** [comment]
+1

**Comment by Nicolab** [comment]
Now the official package can generate the Javascript.

So I just deleted this package: #8
