### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by rokyed** [Nicolab/atom-package-js-generator#4]
[Enter steps to reproduce below:]
1. Install it, crashes right after.

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [package-js-generator](https://github.com/Nicolab/atom-package-js-generator) package, v1.5.0
### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/rokyed/.atom/packages/package-js-generator/node_modules/atom-helpers/lib/utils.js:25

TypeError: Cannot read property 'prototype' of undefined
  at Object.module.exports.extends (/Users/rokyed/.atom/packages/package-js-generator/node_modules/atom-helpers/lib/utils.js:25:26)
  at Object.<anonymous> (/Users/rokyed/.atom/packages/package-js-generator/lib/package-js-generator-view.js:28:16)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/rokyed/.atom/packages/package-js-generator/lib/package-js-generator.js:8:30)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:261:14)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:150:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:187:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:232:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:587:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:378:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
     -0:16.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "projectHome": "/www/mainline"
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.13
break, v0.3.1
git-diff-details, v0.19.0
git-log, v0.4.1
minimap, v4.12.2
pdf-view, v0.23.0
pigments, v0.9.3
tabs-to-spaces, v0.11.0
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by Nicolab** [comment]
See #3
